name: Test Build Zip

on:
  push:
    branches:
      - replay-download

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Client
        run: npm run build

      - name: Zip Game Files
        uses: actions/upload-artifact@v4
        with:
          name: fx-test-game
          path: ./build
